version: "3.3"

services:
  nginx:
    image: nginx
    ports:
      - 81:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    # depends_on:
    #   - core

networks:
  dice-networks:
