name: Deploy Dice Frontend

on:
  push:
    branches:
      - develop

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build --no-cache --rm -f Dockerfile -t pinomaker/dice-frontend:latest .
          docker push pinomaker/dice-frontend:latest
  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Initialize Known Hosts
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts
      - name: Set Permissions for Private Key
        run: |
          echo "${{ secrets.SSH_KEY }}" > $HOME/key.pem
          chmod 400 $HOME/key.pem
      - name: Copy files to VM And Run Application
        run: |
          ssh -i $HOME/key.pem aiara@${{ secrets.VM_HOST }} "sh restart.sh nginx"
